name: langcab_ui
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.langcab.com
#author: florian

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  bootstrap_sass: ^4.1.3
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+19
  angular_components: ^0.10.1
  http: ^0.11.0
  stream_transform: ^0.0.14+1
  firebase: ^5.0.2
  googleapis_auth: ^0.2.6

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  sass_builder: ^2.1.2
  mockito: ^3.0.0-beta+1
  test: ^1.0.0